### ISSUE TITLE
CreateProcess The filename or extension is too long in PollyStatementThread.java

### ISSUE THREAD

**Issue by paratechnical** [Jboonie/PollyCLI#1]
STR:
1. create dir with one UTF 8 txt file 92kb in size(one chapter of a novel)
2.open program, 
4. configure aws, 
3. load previously created folder
3. click convert

Expected: text converted to mp3
Actual:
      Runtime.getRuntime().exec(runString);   in PollyStatementThread.java on line 67 throws an error

java.io.IOException: Cannot run program "cmd.exe": CreateProcess error=206, The filename or extension is too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at pollycli.Logic.PollyStatementThread.run(PollyStatementThread.java:67)
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more

there are 92k chars in runString
I ran the python install where it said that it disabled the maximum char thing, but it doesn't seem to be working or it doesn't seem to apply to runString

**Comment by Jboonie** [comment]
Paratechnical,

Thanks for sending this in! I believe this was probably occurring based on file size, I have released version 2.1.1 which should fix the issue.  [https://github.com/Jboonie/PollyCLI/releases/tag/untagged-77c6ae0ff2e048a51dec](url)
